'use strict';

function generate_visual_simulation({ type, code_snippet, error_description }) {
  const desc = (error_description || '').replace(/'/g, '&#39;');
  const templates = {
    gradient_descent: gradientDescentHTML(desc),
    linear_regression: gradientDescentHTML(desc),
    bst_traversal: bstTraversalHTML(desc),
    merge_sort: mergeSortHTML(desc),
    bubble_sort: bubbleSortHTML(desc),
    neural_net_forward_pass: neuralNetHTML(desc),
    k_means_clustering: kMeansHTML(desc),
  };
  return templates[type] || defaultSimHTML(type, desc);
}

// ─── Gradient Descent ────────────────────────────────────────────────────────
function gradientDescentHTML(desc) {
  return [
    '<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Gradient Descent</title>',
    '<style>',
    'body{margin:0;background:#0a0a0f;color:#fff;font-family:monospace;display:flex;flex-direction:column;align-items:center;padding:20px}',
    'canvas{border:1px solid #00ff9d33;border-radius:8px;margin:10px 0}',
    '.controls{display:flex;gap:10px;margin:10px 0;flex-wrap:wrap;justify-content:center}',
    'button{background:#00ff9d22;border:1px solid #00ff9d;color:#00ff9d;padding:8px 16px;border-radius:6px;cursor:pointer;font-family:monospace}',
    'button:hover{background:#00ff9d44}',
    '.info{color:#00f0ff;font-size:13px;text-align:center;max-width:600px}',
    '.stat{color:#00ff9d;font-size:14px;margin:4px}',
    '</style></head><body>',
    '<h2 style="color:#00ff9d;margin:0">Gradient Descent Visualization</h2>',
    '<p class="info">' + desc + '</p>',
    '<canvas id="c" width="600" height="300"></canvas>',
    '<div class="controls">',
    '<button onclick="togglePlay()">Play / Pause</button>',
    '<button onclick="doStep()">Step</button>',
    '<button onclick="reset()">Reset</button>',
    '<button onclick="changeSpeed()">Speed</button>',
    '</div>',
    '<div class="stat" id="stat">Loss: — | Step: 0</div>',
    '<script>',
    'var c=document.getElementById("c"),ctx=c.getContext("2d");',
    'var x=4.5,lr=0.1,playing=false,stepN=0,speed=1;',
    'function fn(v){return v*v-4*v+5;}',
    'function dfn(v){return 2*v-4;}',
    'function draw(){',
    '  ctx.clearRect(0,0,600,300);',
    '  ctx.strokeStyle="#ffffff11";ctx.lineWidth=1;',
    '  for(var i=0;i<600;i+=50){ctx.beginPath();ctx.moveTo(i,0);ctx.lineTo(i,300);ctx.stroke();}',
    '  for(var i=0;i<300;i+=50){ctx.beginPath();ctx.moveTo(0,i);ctx.lineTo(600,i);ctx.stroke();}',
    '  ctx.beginPath();ctx.strokeStyle="#00f0ff";ctx.lineWidth=2;',
    '  for(var px=0;px<600;px++){var rx=(px/600)*8-1;var ry=fn(rx);var py=300-(ry/10)*300;if(px===0)ctx.moveTo(px,py);else ctx.lineTo(px,py);}',
    '  ctx.stroke();',
    '  var px=(x+1)/8*600,py=300-(fn(x)/10)*300;',
    '  ctx.beginPath();ctx.arc(px,py,8,0,Math.PI*2);ctx.fillStyle="#ff3b5c";ctx.fill();',
    '  ctx.strokeStyle="#fff";ctx.lineWidth=2;ctx.stroke();',
    '  var g=dfn(x),ax=px-g*30;',
    '  ctx.beginPath();ctx.moveTo(px,py);ctx.lineTo(ax,py);ctx.strokeStyle="#00ff9d";ctx.lineWidth=2;ctx.stroke();',
    '  document.getElementById("stat").textContent="Loss: "+fn(x).toFixed(4)+" | Step: "+stepN+" | x: "+x.toFixed(4);',
    '}',
    'function doStep(){x=x-lr*dfn(x);stepN++;draw();}',
    'function togglePlay(){playing=!playing;if(playing)loop();}',
    'function loop(){if(!playing)return;for(var i=0;i<speed;i++)doStep();setTimeout(function(){requestAnimationFrame(loop);},50);}',
    'function reset(){x=4.5;stepN=0;playing=false;draw();}',
    'function changeSpeed(){speed=speed===1?3:speed===3?10:1;}',
    'draw();',
    '<\/script></body></html>',
  ].join('\n');
}

// ─── Bubble Sort ─────────────────────────────────────────────────────────────
function bubbleSortHTML(desc) {
  return [
    '<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Bubble Sort</title>',
    '<style>',
    'body{margin:0;background:#0a0a0f;color:#fff;font-family:monospace;display:flex;flex-direction:column;align-items:center;padding:20px}',
    'canvas{border:1px solid #00ff9d33;border-radius:8px}',
    '.controls{display:flex;gap:10px;margin:10px;flex-wrap:wrap;justify-content:center}',
    'button{background:#00ff9d22;border:1px solid #00ff9d;color:#00ff9d;padding:8px 16px;border-radius:6px;cursor:pointer;font-family:monospace}',
    '.info{color:#00f0ff;font-size:13px;text-align:center;max-width:600px}',
    '.stat{color:#00ff9d;font-size:14px}',
    '</style></head><body>',
    '<h2 style="color:#00ff9d;margin:0">Bubble Sort Visualization</h2>',
    '<p class="info">' + desc + '</p>',
    '<canvas id="c" width="600" height="300"></canvas>',
    '<div class="controls">',
    '<button onclick="togglePlay()">Play / Pause</button>',
    '<button onclick="stepOnce()">Step</button>',
    '<button onclick="reset()">Reset</button>',
    '</div>',
    '<div class="stat" id="stat">Comparisons: 0 | Swaps: 0</div>',
    '<script>',
    'var c=document.getElementById("c"),ctx=c.getContext("2d");',
    'var orig=[64,34,25,12,22,11,90,45,78,33],arr=orig.slice(),i=0,j=0,swaps=0,comps=0,playing=false,done=false;',
    'function draw(){',
    '  ctx.clearRect(0,0,600,300);',
    '  var w=600/arr.length,maxV=Math.max.apply(null,arr);',
    '  for(var idx=0;idx<arr.length;idx++){',
    '    var v=arr[idx],h=(v/maxV)*260,x=idx*w,y=300-h;',
    '    ctx.fillStyle=(idx===j||idx===j+1)?"#ff3b5c":done?"#00ff9d":"#00f0ff44";',
    '    ctx.fillRect(x+2,y,w-4,h);',
    '    ctx.strokeStyle="#00f0ff";ctx.lineWidth=1;ctx.strokeRect(x+2,y,w-4,h);',
    '    ctx.fillStyle="#fff";ctx.font="11px monospace";ctx.textAlign="center";',
    '    ctx.fillText(v,x+w/2,295);',
    '  }',
    '  document.getElementById("stat").textContent="Comparisons: "+comps+" | Swaps: "+swaps;',
    '}',
    'function stepOnce(){',
    '  if(done)return;',
    '  if(j<arr.length-1-i){',
    '    comps++;',
    '    if(arr[j]>arr[j+1]){var t=arr[j];arr[j]=arr[j+1];arr[j+1]=t;swaps++;}',
    '    j++;',
    '  } else {i++;j=0;if(i>=arr.length-1)done=true;}',
    '  draw();',
    '}',
    'function togglePlay(){playing=!playing;if(playing)loop();}',
    'function loop(){if(!playing||done)return;stepOnce();setTimeout(function(){requestAnimationFrame(loop);},200);}',
    'function reset(){arr=orig.slice();i=0;j=0;swaps=0;comps=0;done=false;playing=false;draw();}',
    'draw();',
    '<\/script></body></html>',
  ].join('\n');
}

// ─── Merge Sort ──────────────────────────────────────────────────────────────
function mergeSortHTML(desc) {
  return [
    '<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Merge Sort</title>',
    '<style>',
    'body{margin:0;background:#0a0a0f;color:#fff;font-family:monospace;display:flex;flex-direction:column;align-items:center;padding:20px}',
    'canvas{border:1px solid #00ff9d33;border-radius:8px}',
    '.controls{display:flex;gap:10px;margin:10px;flex-wrap:wrap;justify-content:center}',
    'button{background:#00ff9d22;border:1px solid #00ff9d;color:#00ff9d;padding:8px 16px;border-radius:6px;cursor:pointer;font-family:monospace}',
    '.info{color:#00f0ff;font-size:13px;text-align:center;max-width:600px}',
    '.stat{color:#00ff9d;font-size:14px}',
    '</style></head><body>',
    '<h2 style="color:#00ff9d;margin:0">Merge Sort Visualization</h2>',
    '<p class="info">' + desc + '</p>',
    '<canvas id="c" width="600" height="300"></canvas>',
    '<div class="controls">',
    '<button onclick="togglePlay()">Play / Pause</button>',
    '<button onclick="reset()">Reset</button>',
    '</div>',
    '<div class="stat" id="stat">Step: 0</div>',
    '<script>',
    'var c=document.getElementById("c"),ctx=c.getContext("2d");',
    'var steps=[],stepIdx=0,playing=false;',
    'function recordMergeSort(a,l,r){',
    '  if(l>=r)return;',
    '  var m=Math.floor((l+r)/2);',
    '  recordMergeSort(a,l,m);recordMergeSort(a,m+1,r);',
    '  var left=a.slice(l,m+1),right=a.slice(m+1,r+1),i=0,j=0,k=l;',
    '  while(i<left.length&&j<right.length){',
    '    if(left[i]<=right[j])a[k++]=left[i++];else a[k++]=right[j++];',
    '    steps.push({arr:a.slice(),hl:[k-1]});',
    '  }',
    '  while(i<left.length){a[k++]=left[i++];steps.push({arr:a.slice(),hl:[k-1]});}',
    '  while(j<right.length){a[k++]=right[j++];steps.push({arr:a.slice(),hl:[k-1]});}',
    '}',
    'function init(){var a=[38,27,43,3,9,82,10,64];steps=[];recordMergeSort(a,0,a.length-1);stepIdx=0;}',
    'function draw(s){',
    '  ctx.clearRect(0,0,600,300);',
    '  var cur=s?s.arr:[38,27,43,3,9,82,10,64],hl=s?s.hl:[];',
    '  var w=600/cur.length,maxV=Math.max.apply(null,cur);',
    '  for(var idx=0;idx<cur.length;idx++){',
    '    var v=cur[idx],h=(v/maxV)*260,x=idx*w,y=300-h;',
    '    ctx.fillStyle=hl.indexOf(idx)>=0?"#00ff9d":"#00f0ff44";',
    '    ctx.fillRect(x+2,y,w-4,h);ctx.strokeStyle="#00f0ff";ctx.lineWidth=1;ctx.strokeRect(x+2,y,w-4,h);',
    '    ctx.fillStyle="#fff";ctx.font="13px monospace";ctx.textAlign="center";ctx.fillText(v,x+w/2,295);',
    '  }',
    '  document.getElementById("stat").textContent="Step: "+stepIdx+"/"+steps.length;',
    '}',
    'function togglePlay(){playing=!playing;if(playing)loop();}',
    'function loop(){if(!playing||stepIdx>=steps.length)return;draw(steps[stepIdx++]);setTimeout(function(){requestAnimationFrame(loop);},150);}',
    'function reset(){init();playing=false;draw(steps[0]);}',
    'init();draw(steps[0]);',
    '<\/script></body></html>',
  ].join('\n');
}

// ─── BST Traversal ───────────────────────────────────────────────────────────
function bstTraversalHTML(desc) {
  return [
    '<!DOCTYPE html><html><head><meta charset="UTF-8"><title>BST Traversal</title>',
    '<style>',
    'body{margin:0;background:#0a0a0f;color:#fff;font-family:monospace;display:flex;flex-direction:column;align-items:center;padding:20px}',
    'canvas{border:1px solid #00ff9d33;border-radius:8px}',
    '.controls{display:flex;gap:10px;margin:10px;flex-wrap:wrap;justify-content:center}',
    'button{background:#00ff9d22;border:1px solid #00ff9d;color:#00ff9d;padding:8px 16px;border-radius:6px;cursor:pointer;font-family:monospace}',
    '.info{color:#00f0ff;font-size:13px;text-align:center;max-width:600px}',
    '.stat{color:#00ff9d;font-size:14px}',
    '</style></head><body>',
    '<h2 style="color:#00ff9d;margin:0">BST Traversal Visualization</h2>',
    '<p class="info">' + desc + '</p>',
    '<canvas id="c" width="600" height="340"></canvas>',
    '<div class="controls">',
    '<button onclick="startTraversal(\'inorder\')">Inorder</button>',
    '<button onclick="startTraversal(\'preorder\')">Preorder</button>',
    '<button onclick="startTraversal(\'postorder\')">Postorder</button>',
    '<button onclick="reset()">Reset</button>',
    '</div>',
    '<div class="stat" id="stat">Click a traversal to begin</div>',
    '<script>',
    'var c=document.getElementById("c"),ctx=c.getContext("2d");',
    'var tree={v:50,l:{v:30,l:{v:20,l:null,r:null},r:{v:40,l:null,r:null}},r:{v:70,l:{v:60,l:null,r:null},r:{v:80,l:null,r:null}}};',
    'var visited=[],order=[],idx=0,playing=false;',
    'function setPos(node,x,y,gap){if(!node)return;node.x=x;node.y=y;setPos(node.l,x-gap,y+70,gap/2);setPos(node.r,x+gap,y+70,gap/2);}',
    'setPos(tree,300,40,120);',
    'function drawTree(node,hl){',
    '  if(!node)return;',
    '  if(node.l){ctx.beginPath();ctx.moveTo(node.x,node.y);ctx.lineTo(node.l.x,node.l.y);ctx.strokeStyle="#ffffff33";ctx.lineWidth=2;ctx.stroke();}',
    '  if(node.r){ctx.beginPath();ctx.moveTo(node.x,node.y);ctx.lineTo(node.r.x,node.r.y);ctx.strokeStyle="#ffffff33";ctx.lineWidth=2;ctx.stroke();}',
    '  var isHL=hl&&hl.indexOf(node.v)>=0;',
    '  ctx.beginPath();ctx.arc(node.x,node.y,22,0,Math.PI*2);',
    '  ctx.fillStyle=isHL?"#00ff9d":visited.indexOf(node.v)>=0?"#00f0ff44":"#1a1a2e";',
    '  ctx.fill();ctx.strokeStyle=isHL?"#00ff9d":"#00f0ff";ctx.lineWidth=2;ctx.stroke();',
    '  ctx.fillStyle="#fff";ctx.font="bold 14px monospace";ctx.textAlign="center";ctx.textBaseline="middle";',
    '  ctx.fillText(node.v,node.x,node.y);',
    '  drawTree(node.l,hl);drawTree(node.r,hl);',
    '}',
    'function draw(hl){ctx.clearRect(0,0,600,340);drawTree(tree,hl);}',
    'function inorder(n,res){if(!n)return;inorder(n.l,res);res.push(n.v);inorder(n.r,res);}',
    'function preorder(n,res){if(!n)return;res.push(n.v);preorder(n.l,res);preorder(n.r,res);}',
    'function postorder(n,res){if(!n)return;postorder(n.l,res);postorder(n.r,res);res.push(n.v);}',
    'function startTraversal(type){',
    '  visited=[];order=[];idx=0;playing=true;',
    '  if(type==="inorder")inorder(tree,order);',
    '  else if(type==="preorder")preorder(tree,order);',
    '  else postorder(tree,order);',
    '  loop();',
    '}',
    'function loop(){',
    '  if(!playing||idx>=order.length)return;',
    '  visited.push(order[idx]);',
    '  draw([order[idx]]);',
    '  document.getElementById("stat").textContent="Visiting: "+order[idx]+" | Order: ["+visited.join(", ")+"]";',
    '  idx++;setTimeout(function(){requestAnimationFrame(loop);},700);',
    '}',
    'function reset(){visited=[];order=[];idx=0;playing=false;draw([]);}',
    'draw([]);',
    '<\/script></body></html>',
  ].join('\n');
}

// ─── Neural Net ──────────────────────────────────────────────────────────────
function neuralNetHTML(desc) {
  return [
    '<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Neural Net Forward Pass</title>',
    '<style>',
    'body{margin:0;background:#0a0a0f;color:#fff;font-family:monospace;display:flex;flex-direction:column;align-items:center;padding:20px}',
    'canvas{border:1px solid #00ff9d33;border-radius:8px}',
    '.controls{display:flex;gap:10px;margin:10px;flex-wrap:wrap;justify-content:center}',
    'button{background:#00ff9d22;border:1px solid #00ff9d;color:#00ff9d;padding:8px 16px;border-radius:6px;cursor:pointer;font-family:monospace}',
    '.info{color:#00f0ff;font-size:13px;text-align:center;max-width:600px}',
    '.stat{color:#00ff9d;font-size:14px}',
    '</style></head><body>',
    '<h2 style="color:#00ff9d;margin:0">Neural Network Forward Pass</h2>',
    '<p class="info">' + desc + '</p>',
    '<canvas id="c" width="600" height="320"></canvas>',
    '<div class="controls">',
    '<button onclick="runForward()">Forward Pass</button>',
    '<button onclick="reset()">Reset</button>',
    '</div>',
    '<div class="stat" id="stat">Click Forward Pass to begin</div>',
    '<script>',
    'var c=document.getElementById("c"),ctx=c.getContext("2d");',
    'var layers=[[3,80],[4,200],[4,320],[2,480]];',
    'var activations=[],step=0,playing=false;',
    'function sigmoid(x){return 1/(1+Math.exp(-x));}',
    'function drawNet(activeLayer){',
    '  ctx.clearRect(0,0,600,320);',
    '  for(var li=0;li<layers.length;li++){',
    '    var n=layers[li][0],x=layers[li][1],spacing=320/(n+1);',
    '    for(var i=0;i<n;i++){',
    '      var y=spacing*(i+1);',
    '      if(li<layers.length-1){',
    '        var n2=layers[li+1][0],x2=layers[li+1][1],sp2=320/(n2+1);',
    '        for(var j=0;j<n2;j++){',
    '          ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x2,sp2*(j+1));',
    '          ctx.strokeStyle=activeLayer>li?"#00f0ff44":"#ffffff11";ctx.lineWidth=1;ctx.stroke();',
    '        }',
    '      }',
    '      var act=activations[li]?activations[li][i]:0;',
    '      ctx.beginPath();ctx.arc(x,y,18,0,Math.PI*2);',
    '      ctx.fillStyle=activeLayer===li?"rgba(0,255,157,"+(0.3+act*0.7)+")":"#1a1a2e";',
    '      ctx.fill();ctx.strokeStyle=activeLayer>=li?"#00ff9d":"#00f0ff55";ctx.lineWidth=2;ctx.stroke();',
    '      if(activations[li]){ctx.fillStyle="#fff";ctx.font="10px monospace";ctx.textAlign="center";ctx.textBaseline="middle";ctx.fillText(act.toFixed(2),x,y);}',
    '    }',
    '    var labels=["Input","Hidden 1","Hidden 2","Output"];',
    '    ctx.fillStyle="#00f0ff";ctx.font="11px monospace";ctx.textAlign="center";ctx.fillText(labels[li],x,310);',
    '  }',
    '}',
    'function runForward(){',
    '  activations=[];step=0;playing=true;',
    '  activations[0]=[0.8,0.3,0.6];',
    '  for(var l=1;l<layers.length;l++){',
    '    var prev=activations[l-1],n=layers[l][0],row=[];',
    '    for(var k=0;k<n;k++){var s=0;for(var p=0;p<prev.length;p++)s+=prev[p]*(Math.random()*2-1);row.push(sigmoid(s));}',
    '    activations[l]=row;',
    '  }',
    '  loop();',
    '}',
    'function loop(){',
    '  if(!playing||step>=layers.length)return;',
    '  drawNet(step);',
    '  document.getElementById("stat").textContent="Layer "+step+": "+layers[step][0]+" neurons activated";',
    '  step++;setTimeout(function(){requestAnimationFrame(loop);},800);',
    '}',
    'function reset(){activations=[];step=0;playing=false;drawNet(-1);}',
    'drawNet(-1);',
    '<\/script></body></html>',
  ].join('\n');
}

// ─── K-Means ─────────────────────────────────────────────────────────────────
function kMeansHTML(desc) {
  return [
    '<!DOCTYPE html><html><head><meta charset="UTF-8"><title>K-Means Clustering</title>',
    '<style>',
    'body{margin:0;background:#0a0a0f;color:#fff;font-family:monospace;display:flex;flex-direction:column;align-items:center;padding:20px}',
    'canvas{border:1px solid #00ff9d33;border-radius:8px}',
    '.controls{display:flex;gap:10px;margin:10px;flex-wrap:wrap;justify-content:center}',
    'button{background:#00ff9d22;border:1px solid #00ff9d;color:#00ff9d;padding:8px 16px;border-radius:6px;cursor:pointer;font-family:monospace}',
    '.info{color:#00f0ff;font-size:13px;text-align:center;max-width:600px}',
    '.stat{color:#00ff9d;font-size:14px}',
    '</style></head><body>',
    '<h2 style="color:#00ff9d;margin:0">K-Means Clustering</h2>',
    '<p class="info">' + desc + '</p>',
    '<canvas id="c" width="600" height="320"></canvas>',
    '<div class="controls">',
    '<button onclick="togglePlay()">Play / Pause</button>',
    '<button onclick="stepOnce()">Step</button>',
    '<button onclick="reset()">Reset</button>',
    '</div>',
    '<div class="stat" id="stat">Iteration: 0</div>',
    '<script>',
    'var c=document.getElementById("c"),ctx=c.getContext("2d");',
    'var colors=["#ff3b5c","#00ff9d","#00f0ff","#ffaa00"];',
    'var pts=[],centroids=[],assignments=[],iter=0,playing=false;',
    'function rnd(a,b){return Math.random()*(b-a)+a;}',
    'function init(){',
    '  pts=[];',
    '  for(var i=0;i<60;i++)pts.push([rnd(50,200),rnd(50,270)]);',
    '  for(var i=0;i<40;i++)pts.push([rnd(250,400),rnd(150,270)]);',
    '  for(var i=0;i<40;i++)pts.push([rnd(400,560),rnd(50,200)]);',
    '  centroids=[[100,160],[320,200],[480,120]];',
    '  assignments=new Array(pts.length).fill(0);iter=0;',
    '}',
    'function assign(){',
    '  for(var i=0;i<pts.length;i++){',
    '    var best=0,bd=Infinity;',
    '    for(var ci=0;ci<centroids.length;ci++){',
    '      var d=Math.hypot(pts[i][0]-centroids[ci][0],pts[i][1]-centroids[ci][1]);',
    '      if(d<bd){bd=d;best=ci;}',
    '    }',
    '    assignments[i]=best;',
    '  }',
    '}',
    'function updateCentroids(){',
    '  for(var ci=0;ci<centroids.length;ci++){',
    '    var sx=0,sy=0,cnt=0;',
    '    for(var i=0;i<pts.length;i++){if(assignments[i]===ci){sx+=pts[i][0];sy+=pts[i][1];cnt++;}}',
    '    if(cnt>0){centroids[ci]=[sx/cnt,sy/cnt];}',
    '  }',
    '}',
    'function draw(){',
    '  ctx.clearRect(0,0,600,320);',
    '  for(var i=0;i<pts.length;i++){ctx.beginPath();ctx.arc(pts[i][0],pts[i][1],5,0,Math.PI*2);ctx.fillStyle=colors[assignments[i]];ctx.fill();}',
    '  for(var ci=0;ci<centroids.length;ci++){',
    '    ctx.beginPath();ctx.arc(centroids[ci][0],centroids[ci][1],12,0,Math.PI*2);',
    '    ctx.fillStyle=colors[ci];ctx.fill();ctx.strokeStyle="#fff";ctx.lineWidth=3;ctx.stroke();',
    '    ctx.fillStyle="#fff";ctx.font="bold 11px monospace";ctx.textAlign="center";ctx.textBaseline="middle";',
    '    ctx.fillText("C"+(ci+1),centroids[ci][0],centroids[ci][1]);',
    '  }',
    '  document.getElementById("stat").textContent="Iteration: "+iter;',
    '}',
    'function stepOnce(){assign();updateCentroids();iter++;draw();}',
    'function togglePlay(){playing=!playing;if(playing)loop();}',
    'function loop(){if(!playing)return;stepOnce();setTimeout(function(){requestAnimationFrame(loop);},600);}',
    'function reset(){init();assign();draw();}',
    'init();assign();draw();',
    '<\/script></body></html>',
  ].join('\n');
}

// ─── Default ─────────────────────────────────────────────────────────────────
function defaultSimHTML(type, desc) {
  return [
    '<!DOCTYPE html><html><head><meta charset="UTF-8"><title>Simulation</title>',
    '<style>body{margin:0;background:#0a0a0f;color:#fff;font-family:monospace;display:flex;flex-direction:column;align-items:center;justify-content:center;height:100vh;text-align:center;padding:20px}h2{color:#00ff9d}p{color:#00f0ff;max-width:500px}</style>',
    '</head><body>',
    '<h2>' + (type || 'Simulation') + '</h2>',
    '<p>' + (desc || 'Interactive simulation') + '</p>',
    '</body></html>',
  ].join('\n');
}

module.exports = { generate_visual_simulation };
